name: flutter_tv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  window_manager: ^0.3.8
  cached_network_image: ^3.3.1
  html: ^0.15.4
  dio: ^5.4.0
  shimmer: ^3.0.0
  pagination_flutter: ^0.0.8
  video_player: ^2.8.2
  common_utils: ^2.1.0
  auto_orientation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
