name: flutter_tv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  window_manager: ^0.3.8
  cached_network_image: ^3.3.1
  flick_video_player: ^0.7.0
  html: ^0.15.4
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
